# Copy this file for your setup:
#
aws:

  # Credentials:
  #
  accessKeyId: <Access Key ID>
  secretAccessKey: <Secret Access Key>

  # Region, which must be one of:
  #
  #  us-east-1, us-west-1, us-west-2, eu-west-1, ap-southeast-1, ap-northeast-1
  #
  #region: eu-west-1

  sqs:
    #visibilityTimeout: 120
